### ISSUE TITLE
Config.yml not loading

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/AdvancedTabOverlay#1]
I installed this plugin on my desktop server using PaperMC 1.14.4 and latest dev build of ProtocolLib.

It generated the tablist and icons folder and also loaded those files.
However, it didn't create the config.yml.

**Comment by CodeCrafter47** [comment]
There is no `config.yml` yet. It will be added at a later point in time when I figure out what should be configured there.

**Comment by Andre601** [comment]
I have some suggestions:
- Global Player sets
- Global Custom placeholders
- Blacklist for worlds (to deny tablist being modified in those worlds.)
- World overwrite (To f.e. have only "survival" for world, world\_the_end and world\_nether)
