### ISSUE TITLE
Invalid header links in Wiki's Placeholder's page

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/AdvancedTabOverlay#11]
Looking at [latest commit for the Placeholders page](https://github.com/CodeCrafter47/AdvancedTabOverlay/wiki/Placeholders/_compare/b2c1ce4%5E...b2c1ce4) is there an issue with the links to the headers.

Namely...

- `#time-<format>` is invalid. Right text: `time-format`
- `#playerset:<name>-size` is invalid. Right text: `#playersetname-size`

Tl;dr is, that GitHub strips special characters such as `$`, `<`, `>`, `:` and similar away and the above links should be corrected.

**Comment by CodeCrafter47** [comment]
Fixed!
