### ISSUE TITLE
Not working team colors

### ISSUE THREAD

**Issue by gwladyka** [CodeCrafter47/AdvancedTabOverlay#12]
Plugin messes up the vanilla /team. The colors are not displayed in the nametags(above player head), after adding player to the team, e.g. "red". Everything fine, after removing the plugin.

**Comment by Andre601** [comment]
Can you provide a reproducable example?
Like what steps to get this? What plugins? Server version?

**Comment by gwladyka** [comment]
1.16.3
1. Start server with ATO
2. Do /team add red and /Team join red Nickname
3. Do /team modify red color red
4. See colors on death messages but not on the nametags above player head
5. Stop server, delete plugin and start server
6. Now you can see Team colors.
